User address on subscription details base
common-group/services-core-db pull request #80
Opened 2018-06-05 13:52 UTC by grpse

### Why

Added new function user_details to get users information as json. There is some checks about user requesting address of user to test if this user is contributing to some of requester projects.

### Wrap up checklist

- [X] All new code has tests
- [X] Comments's added to columns / views / functions ([ADD COMMENT](https://www.postgresql.org/docs/9.4/static/sql-comment.html)...) 
- [ ] Code is documented on docs? link PR from [docs repo](https://github.com/common-group/common)
- [ ] Code is reviewed

2018-06-05 15:18 UTC, devton requested changes

2018-06-05 15:18 UTC, devton commented on migrations/2018-06-05-130001_user_details_on_community_api/up.sql
> +CREATE OR REPLACE FUNCTION community_service_api.user_details(user_id uuid)
lets use only id instead user_id, theses params are mapped on request

2018-06-05 15:18 UTC, devton commented on migrations/2018-06-05-130001_user_details_on_community_api/up.sql
> +                'id', _user.id,
we can return the external_id too

2018-06-05 15:18 UTC, devton commented on specs/sql-specs/community-service-api/function.user_details_test.sql
> +    create or replace function test_access_with_scoped_to_user_details()
add more tests for platform_user role and anonymous role

2018-06-05 22:15 UTC, grpse commented
all changes made and docs added (i made a PR to common docs)

2018-06-06 00:01 UTC, devton approved these changes

2018-06-06 00:01 UTC, merged